
name: Conservación de Islas
on: [push, pull_request]

jobs:
  actions:
    runs-on: ubuntu-18.04
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/dummy_transformations .
    - name: Corre pruebas
      run: docker run --volume ${PWD}:/workdir islasgeci/dummy_transformations make tests
    - name: Verifica resistencia a mutaciones
      run: docker run --volume ${PWD}:/workdir islasgeci/dummy_transformations make mutants
    - name: Verifica el formato
      run: docker run --volume ${PWD}:/workdir islasgeci/dummy_transformations make lint
